services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/joyreyesdimaculangan/portfolio-laravel.git
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - fromGroup: laravel-env

