services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/joyreyesdimaculangan/portfolio-laravel.git
    branch: main
    dockerfilePath: Dockerfile
    ports:
      - 8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://joy-dimaculangan.onrender.com
